# A lot of the STL code was generated by Gemini
import flask
from flask import *
from version import *
from configmanager import *
from validators import ValidationError, validate_printer_profile, validate_selection_data, validate_ip_address
import requests
import json as json_module
import os
import uuid
import zipfile
import math
import xml.etree.ElementTree as ET
import shutil
import subprocess
from werkzeug.utils import secure_filename
from print3r_parser import build_print3r_plate_commands
app = Flask(__name__)
config = ConfigManager()
with open("teapot.cfg", "r") as f:
    t = f.read().strip() == "True"

def seed_demo_project():
    try:
        base_dir = os.path.dirname(os.path.abspath(__file__))
        template_path = os.path.join(base_dir, "demo", "demo_block.json")
        if not os.path.exists(template_path):
            return
        projects_dir = os.path.join(base_dir, "projects")
        os.makedirs(projects_dir, exist_ok=True)
        target_path = os.path.join(projects_dir, "Demo Block.json")
        if not os.path.exists(target_path):
            shutil.copy2(template_path, target_path)
            return

        # One-time migration for older demo project URLs.
        with open(target_path, "r") as f:
            existing = json_module.load(f)
        model_block = existing.get("models", {})
        models = model_block.get("models", []) if isinstance(model_block, dict) else []
        needs_migration = any(
            isinstance(m, dict) and m.get("url", "").startswith("/static/uploads/block_demo")
            for m in models
        )
        if needs_migration:
            shutil.copy2(template_path, target_path)
    except Exception as e:
        print(f"Failed to seed demo project: {e}")

seed_demo_project()

UNIT_TO_MM = {
    "micron": 0.001,
    "millimeter": 1.0,
    "centimeter": 10.0,
    "inch": 25.4,
    "foot": 304.8,
    "meter": 1000.0
}

PRINT3R_PROFILE_ORDER = [
    "machine_name",
    "machine_width",
    "machine_depth",
    "machine_height",
    "nozzle_diameter",
    "filament_diameter",
    "temperature",
    "bed_temperature",
    "layer_height",
    "first_layer_height",
    "first_layer_temperature",
    "first_layer_bed_temperature",
    "fill_density",
    "infill_pattern",
    "perimeters",
    "wall_thickness",
    "top_layers",
    "top_thickness",
    "bottom_layers",
    "bottom_thickness",
    "print_speed",
    "first_layer_speed",
    "perimeter_speed",
    "small_perimeter_speed",
    "travel_speed",
    "infill_speed",
    "bridge_speed",
    "retraction_length",
    "retract_speed",
    "skirts",
    "brims",
    "rafts",
    "support",
    "support_angle",
    "support_density",
    "support_interface_layers",
    "support_z_distance",
    "support_xy_distance",
    "support_pattern",
    "support_speed",
    "support_interface_speed",
    "seam",
    "cool_fan_speed",
    "cool_fan_speed_max",
    "cool_fan_speed_min",
    "start_gcode",
    "end_gcode",
]


def _sanitize_project_ini_name(project_name):
    safe = secure_filename(str(project_name or "").strip())
    return safe or "project"


def _build_print3r_defaults(selected_printer):
    printer = selected_printer if isinstance(selected_printer, dict) else {}
    bed = printer.get("bed_size") if isinstance(printer.get("bed_size"), list) else [220, 220, 250]
    speed = printer.get("speed_settings") if isinstance(printer.get("speed_settings"), dict) else {}
    hotend = printer.get("hotend_temp") if isinstance(printer.get("hotend_temp"), dict) else {}
    bed_temp = printer.get("bed_temp") if isinstance(printer.get("bed_temp"), dict) else {}
    retraction = printer.get("retraction") if isinstance(printer.get("retraction"), dict) else {}
    nozzle_size = float(printer.get("nozzle_size", 0.4))
    default_layer = round(max(0.05, min(nozzle_size * 0.8, nozzle_size * 0.5)), 3)

    return {
        "machine_name": str(printer.get("name", "Katana Printer")),
        "machine_width": float(bed[0]) if len(bed) > 0 else 220.0,
        "machine_depth": float(bed[1]) if len(bed) > 1 else 220.0,
        "machine_height": float(bed[2]) if len(bed) > 2 else 250.0,
        "nozzle_diameter": nozzle_size,
        "filament_diameter": float(printer.get("filament_diameter", 1.75)),
        "temperature": int(hotend.get("max", hotend.get("min", 200))),
        "bed_temperature": int(bed_temp.get("max", bed_temp.get("min", 60))),
        "layer_height": default_layer,
        "first_layer_height": default_layer,
        "first_layer_temperature": int(hotend.get("max", hotend.get("min", 205))),
        "first_layer_bed_temperature": int(bed_temp.get("max", bed_temp.get("min", 60))),
        "fill_density": 20,
        "infill_pattern": "grid",
        "perimeters": 2,
        "wall_thickness": 0.0,
        "top_layers": 2,
        "top_thickness": 0.0,
        "bottom_layers": 2,
        "bottom_thickness": 0.0,
        "print_speed": int(speed.get("print_speed", 50)),
        "first_layer_speed": max(10, int(speed.get("print_speed", 50) * 0.5)),
        "perimeter_speed": int(speed.get("outer_wall_speed", 40)),
        "small_perimeter_speed": int(speed.get("outer_wall_speed", 35)),
        "travel_speed": int(speed.get("travel_speed", 150)),
        "infill_speed": int(speed.get("infill_speed", 60)),
        "bridge_speed": int(speed.get("infill_speed", 60)),
        "retraction_length": float(retraction.get("distance", 2.0)),
        "retract_speed": int(retraction.get("speed", 35)),
        "skirts": 2,
        "brims": 0,
        "rafts": 0,
        "support": "none",
        "support_angle": 60,
        "support_density": 15,
        "support_interface_layers": 2,
        "support_z_distance": 0.2,
        "support_xy_distance": 0.7,
        "support_pattern": "grid",
        "support_speed": int(speed.get("infill_speed", 60)),
        "support_interface_speed": int(speed.get("infill_speed", 60)),
        "seam": "aligned",
        "cool_fan_speed": 100,
        "cool_fan_speed_max": 100,
        "cool_fan_speed_min": 35,
        "start_gcode": str(printer.get("gcode_start", "")),
        "end_gcode": str(printer.get("gcode_end", "")),
    }


def _normalize_print3r_settings(settings, defaults):
    merged = defaults.copy()
    if not isinstance(settings, dict):
        return merged

    for key, value in settings.items():
        if key not in defaults:
            continue
        if value is None:
            continue
        if isinstance(value, str):
            stripped = value.strip()
            if stripped == "":
                continue
            value = stripped
        merged[key] = value

    numeric_fields = {
        "machine_width": float,
        "machine_depth": float,
        "machine_height": float,
        "nozzle_diameter": float,
        "filament_diameter": float,
        "temperature": int,
        "bed_temperature": int,
        "layer_height": float,
        "first_layer_height": float,
        "first_layer_temperature": int,
        "first_layer_bed_temperature": int,
        "fill_density": int,
        "perimeters": int,
        "wall_thickness": float,
        "top_layers": int,
        "top_thickness": float,
        "bottom_layers": int,
        "bottom_thickness": float,
        "print_speed": int,
        "first_layer_speed": int,
        "perimeter_speed": int,
        "small_perimeter_speed": int,
        "travel_speed": int,
        "infill_speed": int,
        "bridge_speed": int,
        "retraction_length": float,
        "retract_speed": int,
        "skirts": int,
        "brims": int,
        "rafts": int,
        "support_angle": int,
        "support_density": int,
        "support_interface_layers": int,
        "support_z_distance": float,
        "support_xy_distance": float,
        "support_speed": int,
        "support_interface_speed": int,
        "cool_fan_speed": int,
        "cool_fan_speed_max": int,
        "cool_fan_speed_min": int,
    }
    for field, cast in numeric_fields.items():
        try:
            merged[field] = cast(merged[field])
        except (TypeError, ValueError):
            merged[field] = defaults[field]

    merged["support"] = str(merged.get("support", "none"))
    merged["support_pattern"] = str(merged.get("support_pattern", "grid"))
    merged["infill_pattern"] = str(merged.get("infill_pattern", "grid"))
    merged["seam"] = str(merged.get("seam", "aligned"))
    merged["start_gcode"] = str(merged.get("start_gcode", ""))
    merged["end_gcode"] = str(merged.get("end_gcode", ""))
    merged["machine_name"] = str(merged.get("machine_name", "Katana Printer"))
    return merged


def _render_print3r_ini(settings):
    lines = []
    for key in PRINT3R_PROFILE_ORDER:
        value = settings.get(key, "")
        if isinstance(value, float):
            if value.is_integer():
                value = int(value)
            else:
                value = f"{value:.3f}".rstrip("0").rstrip(".")
        text = str(value).replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\n")
        lines.append(f"{key}={text}")
    return "\n".join(lines) + "\n"


def _resolve_project_json_path_from_payload(payload):
    base_dir = os.path.dirname(os.path.abspath(__file__))
    projects_dir = os.path.join(base_dir, "projects")

    def _safe_project_stem(name):
        return "".join([c for c in str(name) if c.isalnum() or c in (' ', '.', '_', '-')]).strip()

    project_filename = str(payload.get("project_filename", "")).strip()
    if project_filename:
        if os.path.basename(project_filename) != project_filename:
            raise ValueError("Invalid project filename")
        if ".." in project_filename or not project_filename.endswith(".json"):
            raise ValueError("Invalid project filename")
        return os.path.join(projects_dir, project_filename)

    project_name = str(payload.get("project_name", "")).strip()
    if not project_name:
        raise ValueError("project_name or project_filename is required")
    safe_name = _safe_project_stem(project_name)
    if not safe_name:
        raise ValueError("Invalid project name")
    return os.path.join(projects_dir, f"{safe_name}.json")


def _resolve_profile_ini_path_from_payload(payload):
    base_dir = os.path.dirname(os.path.abspath(__file__))
    printer_settings_dir = os.path.join(base_dir, "settings", "printer")
    settings_dir = os.path.join(base_dir, "settings")

    profile_name = str(payload.get("profile_name", "")).strip()
    if profile_name:
        safe_name = secure_filename(profile_name)
        if not safe_name:
            raise ValueError("Invalid profile name")
        primary = os.path.join(printer_settings_dir, f"{safe_name}.ini")
        fallback = os.path.join(settings_dir, f"{safe_name}.ini")
        return primary if os.path.exists(primary) else fallback

    ini_filename = str(payload.get("ini_filename", "")).strip()
    if ini_filename:
        if os.path.basename(ini_filename) != ini_filename:
            raise ValueError("Invalid INI filename")
        if ".." in ini_filename or not ini_filename.endswith(".ini"):
            raise ValueError("Invalid INI filename")
        safe_file = ini_filename
        primary = os.path.join(printer_settings_dir, safe_file)
        fallback = os.path.join(settings_dir, safe_file)
        return primary if os.path.exists(primary) else fallback

    project_name = str(payload.get("project_name", "")).strip()
    if not project_name:
        raise ValueError("profile_name, ini_filename, or project_name is required")
    safe_project = secure_filename(project_name)
    if not safe_project:
        raise ValueError("Invalid project name")
    primary = os.path.join(printer_settings_dir, f"{safe_project}.ini")
    fallback = os.path.join(settings_dir, f"{safe_project}.ini")
    return primary if os.path.exists(primary) else fallback

def _compute_normal(a, b, c):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    length = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
    return nx / length, ny / length, nz / length

def _write_ascii_stl(path, solid_name, vertices, triangles, scale):
    with open(path, "w") as f:
        f.write(f"solid {solid_name}\n")
        for i1, i2, i3 in triangles:
            a = (vertices[i1][0] * scale, vertices[i1][1] * scale, vertices[i1][2] * scale)
            b = (vertices[i2][0] * scale, vertices[i2][1] * scale, vertices[i2][2] * scale)
            c = (vertices[i3][0] * scale, vertices[i3][1] * scale, vertices[i3][2] * scale)
            nx, ny, nz = _compute_normal(a, b, c)
            f.write(f"  facet normal {nx} {ny} {nz}\n")
            f.write("    outer loop\n")
            f.write(f"      vertex {a[0]} {a[1]} {a[2]}\n")
            f.write(f"      vertex {b[0]} {b[1]} {b[2]}\n")
            f.write(f"      vertex {c[0]} {c[1]} {c[2]}\n")
            f.write("    endloop\n")
            f.write("  endfacet\n")
        f.write(f"endsolid {solid_name}\n")

def _extract_3mf_models(file_storage, upload_dir, base_name):
    file_storage.stream.seek(0)
    generated = []
    with zipfile.ZipFile(file_storage.stream) as zf:
        model_entries = [name for name in zf.namelist() if name.lower().endswith(".model")]
        if not model_entries:
            raise ValueError("No .model payload found in 3MF file")

        for model_entry in model_entries:
            root = ET.fromstring(zf.read(model_entry))
            ns_uri = root.tag[root.tag.find("{") + 1:root.tag.find("}")]
            ns = {"m": ns_uri}
            scale = UNIT_TO_MM.get(root.attrib.get("unit", "millimeter"), 1.0)

            resources = root.find("m:resources", ns)
            if resources is None:
                continue

            for obj in resources.findall("m:object", ns):
                mesh = obj.find("m:mesh", ns)
                if mesh is None:
                    continue

                vertices_tag = mesh.find("m:vertices", ns)
                triangles_tag = mesh.find("m:triangles", ns)
                if vertices_tag is None or triangles_tag is None:
                    continue

                vertices = []
                for vtx in vertices_tag.findall("m:vertex", ns):
                    vertices.append((
                        float(vtx.attrib.get("x", 0.0)),
                        float(vtx.attrib.get("y", 0.0)),
                        float(vtx.attrib.get("z", 0.0))
                    ))

                triangles = []
                for tri in triangles_tag.findall("m:triangle", ns):
                    i1 = int(tri.attrib.get("v1", 0))
                    i2 = int(tri.attrib.get("v2", 0))
                    i3 = int(tri.attrib.get("v3", 0))
                    if i1 < len(vertices) and i2 < len(vertices) and i3 < len(vertices):
                        triangles.append((i1, i2, i3))

                if not vertices or not triangles:
                    continue

                obj_id = obj.attrib.get("id", "model")
                out_name = secure_filename(f"{base_name}_{obj_id}_{uuid.uuid4().hex[:8]}.stl")
                out_path = os.path.join(upload_dir, out_name)
                _write_ascii_stl(out_path, f"{base_name}_{obj_id}", vertices, triangles, scale)
                generated.append({
                    "filename": out_name,
                    "url": f"/static/uploads/{out_name}"
                })
    return generated
@app.route('/')
def load():
    if t:
        return abort(418) # See RFC 2324
    if config.check_config("config.json"):
        config.load_config("config.json")
        return render_template('index.html', version=v, page_title="Katana", project_name="Untitled",ipaddress=config.get_ip_address())
    else:
        return render_template('welcomeflow.html', version=v, page_title="Katana", project_name="None")
    

@app.route('/welcome')
def welcome():
    return render_template('welcomeflow.html', version=v, page_title="Katana", project_name="None")

@app.route('/demo/block.stl')
def demo_block_stl():
    return send_file("block.stl")

@app.route('/download_setup')
def download_setup():
    return render_template('download-setup.html', version=v, page_title="Katana - Download Configuration", project_name="None")

@app.route('/printer_setup')
def printer_setup():
    try:
        # Load prebuilt profiles
        config.load_printer_profiles("printers/printer-settings.json")
        prebuilt_profiles = config.get_printer_profiles()
        
        # Load saved config
        config.load_config("config.json")
        saved_printers = config.get_saved_printers()
        
        return render_template('printer-setup.html', 
                             version=v, 
                             page_title="Katana - Printer Setup",
                             profiles=prebuilt_profiles,
                             saved_printers=saved_printers,
                             project_name="None")
    except Exception as e:
        print(f"ERROR in printer_setup: {e}")
        # Return a simple error page to prevent loops
        return render_template('index.html', 
                          version=v, 
                          page_title="Katana - Error")

@app.route('/save_custom_printer', methods=['POST'])
def save_custom_printer():
    try:
        # Get and validate JSON data
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"})
        
        printer_data = request.get_json()
        if not printer_data:
            return jsonify({"success": False, "error": "No data provided"})
        
        # Validate the printer profile
        validated_data = validate_printer_profile(printer_data)
        
        # Load current config
        config.load_config("config.json")
        
        # Save the validated custom printer
        config.save_printer_to_config(validated_data)
        config.save_config("config.json")
        
        return jsonify({"success": True})
    except ValidationError as e:
        return jsonify({"success": False, "error": str(e)})
    except Exception as e:
        return jsonify({"success": False, "error": "Internal server error"})

@app.route('/save_printer_selection', methods=['POST'])
def save_printer_selection():
    try:
        # Get and validate JSON data
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"})
        
        data = request.get_json()
        if not data:
            return jsonify({"success": False, "error": "No data provided"})
        
        # Validate selection data
        index, profile_type = validate_selection_data(data)
        
        # Get IP address if provided (for prebuilt profiles)
        ip_address = data.get('ip_address', '').strip()
        
        # Load current config and printer profiles
        config.load_config("config.json")
        config.load_printer_profiles("printers/printer-settings.json")
        
        # Get the actual profile data with bounds checking
        if profile_type == 'prebuilt':
            # Get prebuilt profile by index
            profiles = config.get_printer_profiles()
            if index >= len(profiles):
                return jsonify({"success": False, "error": "Invalid profile index"})
            profile_data = profiles[index].copy()  # Make a copy to modify
            
            # Update IP address if provided
            if ip_address:
                # Validate IP address
                validated_ip = validate_ip_address(ip_address)
                profile_data['ip_address'] = validated_ip
            else:
                profile_data['ip_address'] = ''
                
        elif profile_type == 'saved':
            # Get saved profile by index
            saved_printers = config.get_saved_printers()
            if index >= len(saved_printers):
                return jsonify({"success": False, "error": "Invalid saved profile index"})
            profile_data = saved_printers[index]['data']
        else:
            return jsonify({"success": False, "error": "Invalid profile type"})
        
        # Save the full profile data
        if "selected_printer" not in config.config:
            config.config["selected_printer"] = {}
        
        config.config["selected_printer"] = profile_data
        config.save_config("config.json")
        
        return jsonify({"success": True})
    except ValidationError as e:
        return jsonify({"success": False, "error": str(e)})
    except Exception as e:
        return jsonify({"success": False, "error": "Internal server error"})


@app.route('/api/config')
def get_current_config():
    try:
        config.load_config("config.json")
        return jsonify(config.config)
    except Exception as e:
        return jsonify({"success": False, "error": "Failed to load config"})


@app.route('/api/print3r/default_settings', methods=['GET'])
def get_print3r_defaults():
    try:
        config.load_config("config.json")
        selected_printer = config.config.get("selected_printer", {})
        defaults = _build_print3r_defaults(selected_printer)
        return jsonify({"success": True, "settings": defaults})
    except Exception as e:
        return jsonify({"success": False, "error": "Failed to load defaults"})


@app.route('/api/print3r/generate_profile', methods=['POST'])
def generate_print3r_profile():
    try:
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"})

        payload = request.get_json() or {}
        project_name = payload.get("project_name", "")
        if not str(project_name).strip():
            return jsonify({"success": False, "error": "Project name is required"})

        config.load_config("config.json")
        selected_printer = config.config.get("selected_printer", {})
        defaults = _build_print3r_defaults(selected_printer)
        settings = _normalize_print3r_settings(payload.get("settings", {}), defaults)
        settings["machine_name"] = str(project_name).strip()

        base_dir = os.path.dirname(os.path.abspath(__file__))
        settings_dir = os.path.join(base_dir, "settings")
        printer_dir = os.path.join(settings_dir, "printer")
        os.makedirs(printer_dir, exist_ok=True)

        profile_name = _sanitize_project_ini_name(project_name)
        filename = f"{profile_name}.ini"
        profile_path = os.path.join(printer_dir, filename)
        ini_data = _render_print3r_ini(settings)

        with open(profile_path, "w") as f:
            f.write(ini_data)

        # Compatibility copy for tools/workflows expecting ./settings/<name>.ini.
        root_profile_path = os.path.join(settings_dir, filename)
        with open(root_profile_path, "w") as f:
            f.write(ini_data)

        return jsonify({
            "success": True,
            "profile_name": profile_name,
            "filename": filename,
            "path": f"./settings/printer/{filename}",
            "compat_path": f"./settings/{filename}"
        })
    except Exception as e:
        return jsonify({"success": False, "error": "Failed to generate Print3r profile"})


@app.route('/api/print3r/parse_commands', methods=['POST'])
def parse_print3r_commands():
    try:
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"})

        payload = request.get_json() or {}
        project_json_path = _resolve_project_json_path_from_payload(payload)
        ini_path = _resolve_profile_ini_path_from_payload(payload)
        slicer = str(payload.get("slicer", "slic3r")).strip() or "slic3r"
        bake_models = payload.get("bake_models", True)
        if isinstance(bake_models, str):
            bake_models = bake_models.lower() not in ("0", "false", "no", "off")
        bake_models = bool(bake_models)

        if not os.path.exists(project_json_path):
            return jsonify({"success": False, "error": "Project JSON not found"})
        if not os.path.exists(ini_path):
            return jsonify({"success": False, "error": "Project INI not found"})

        parsed = build_print3r_plate_commands(
            project_ini_path=ini_path,
            project_json_path=project_json_path,
            slicer=slicer,
            bake_models=bake_models
        )
        return jsonify({"success": True, "parsed": parsed})
    except ValueError as e:
        return jsonify({"success": False, "error": str(e)})
    except Exception as e:
        return jsonify({"success": False, "error": "Failed to parse Print3r commands"})


def _inject_print3r_verbose(argv):
    if not isinstance(argv, list):
        return []
    clean = [str(x) for x in argv if str(x).strip()]
    if not clean:
        return []
    if clean[0] != "print3r":
        raise ValueError("Only print3r commands are allowed")
    if "-vv" in clean or "-v" in clean or "--verbose" in clean:
        return clean
    return [clean[0], "-vv", *clean[1:]]


@app.route('/api/print3r/stream_run', methods=['POST'])
def stream_run_print3r_command():
    try:
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"}), 400

        payload = request.get_json() or {}
        argv = payload.get("argv", [])
        cmd = _inject_print3r_verbose(argv)
        if not cmd:
            return jsonify({"success": False, "error": "Invalid command"}), 400

        base_dir = os.path.dirname(os.path.abspath(__file__))
        settings_dir = os.path.join(base_dir, "settings")
        os.makedirs(settings_dir, exist_ok=True)

        def generate():
            yield f"$ {' '.join(cmd)}\n"
            try:
                proc = subprocess.Popen(
                    cmd,
                    cwd=base_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    bufsize=1,
                    env={**os.environ, "PRINT3R": f"settings={settings_dir}"}
                )
            except Exception as e:
                yield f"[error] failed to launch command: {e}\n"
                return

            try:
                if proc.stdout:
                    for line in proc.stdout:
                        yield line
                code = proc.wait()
                yield f"\n[katana] process exited with code {code}\n"
            finally:
                if proc.stdout:
                    proc.stdout.close()

        return Response(stream_with_context(generate()), mimetype='text/plain')
    except ValueError as e:
        return jsonify({"success": False, "error": str(e)}), 400
    except Exception as e:
        return jsonify({"success": False, "error": "Failed to run Print3r command"}), 500


@app.route('/api/print3r/gcode/<filename>', methods=['GET'])
def get_gcode_file(filename):
    try:
        base_dir = os.path.dirname(os.path.abspath(__file__))
        gcode_dir = os.path.join(base_dir, "gcode")
        safe_filename = secure_filename(filename)
        if safe_filename != filename or not safe_filename.endswith(".gcode"):
            return jsonify({"success": False, "error": "Invalid filename"}), 400
        
        return send_from_directory(gcode_dir, safe_filename)
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route('/api/gcode/preview/<filename>', methods=['GET'])
def gcode_preview(filename):
    try:
        base_dir = os.path.dirname(os.path.abspath(__file__))
        gcode_dir = os.path.join(base_dir, "gcode")
        safe_filename = secure_filename(filename)
        if safe_filename != filename or not safe_filename.endswith(".gcode"):
            return jsonify({"success": False, "error": "Invalid filename"}), 400

        path = os.path.join(gcode_dir, safe_filename)
        if not os.path.exists(path):
            return jsonify({"success": False, "error": "G-code not found"}), 404

        line_count = 0
        layer_count = 0
        max_x = 0.0
        max_y = 0.0
        max_z = 0.0
        extrusion = 0.0
        preview_lines = []

        with open(path, "r", errors="ignore") as f:
            for raw in f:
                line = raw.strip()
                line_count += 1
                if line_count <= 200:
                    preview_lines.append(line)

                upper = line.upper()
                if upper.startswith(";LAYER:") or upper.startswith("; LAYER:"):
                    layer_count += 1
                if upper.startswith("G1") or upper.startswith("G0"):
                    parts = line.split()
                    for part in parts:
                        if len(part) < 2:
                            continue
                        axis = part[0].upper()
                        try:
                            value = float(part[1:])
                        except ValueError:
                            continue
                        if axis == "X":
                            max_x = max(max_x, value)
                        elif axis == "Y":
                            max_y = max(max_y, value)
                        elif axis == "Z":
                            max_z = max(max_z, value)
                        elif axis == "E":
                            extrusion = max(extrusion, value)

        return jsonify({
            "success": True,
            "filename": safe_filename,
            "path": path,
            "metadata": {
                "line_count": line_count,
                "layer_count": layer_count,
                "max_x": round(max_x, 3),
                "max_y": round(max_y, 3),
                "max_z": round(max_z, 3),
                "max_extrusion": round(extrusion, 3)
            },
        "preview_lines": preview_lines
    })
    except Exception:
        return jsonify({"success": False, "error": "Failed to read G-code preview"}), 500


@app.route('/api/gcode/upload', methods=['POST'])
def upload_gcode():
    try:
        if not request.is_json:
            return jsonify({"success": False, "error": "JSON body required"}), 400
        data = request.get_json()
        filename = data.get("filename", "")
        if not filename:
            return jsonify({"success": False, "error": "filename required"}), 400
        safe_name = secure_filename(filename)
        if safe_name != filename or not safe_name.endswith(".gcode"):
            return jsonify({"success": False, "error": "Invalid filename"}), 400

        base_dir = os.path.dirname(os.path.abspath(__file__))
        gcode_dir = os.path.join(base_dir, "gcode")
        path = os.path.join(gcode_dir, safe_name)
        if not os.path.exists(path):
            return jsonify({"success": False, "error": "G-code file not found"}), 404

        config.load_config("config.json")
        printer_url = config.get_ip_address()
        if not printer_url or printer_url == "about:blank":
            return jsonify({"success": False, "error": "No printer IP configured"}), 400

        upload_url = printer_url.rstrip("/") + "/rr_upload"
        with open(path, "rb") as f:
            files = {"file": (safe_name, f, "application/octet-stream")}
            try:
                response = requests.post(upload_url, files=files, timeout=30)
                response.raise_for_status()
            except requests.RequestException as exc:
                return jsonify({"success": False, "error": f"Upload failed: {exc}"}), 500

        return jsonify({"success": True, "message": "Uploaded", "url": upload_url})
    except Exception:
        return jsonify({"success": False, "error": "Upload failed"}), 500


@app.route('/api/projects', methods=['GET'])
def list_projects():
    try:
        projects = config.list_projects()
        return jsonify(projects)
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route('/api/projects', methods=['POST'])
def save_project():
    try:
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"})
        
        data = request.get_json()
        name = data.get('name', '').strip()
        project_data = data.get('data')
        previous_filename = data.get('previous_filename')
        
        if not name or not project_data:
            return jsonify({"success": False, "error": "Name and data are required"})
            
        success, result = config.save_project(name, project_data, previous_filename=previous_filename)
        if success:
            return jsonify({"success": True, "filename": result})
        else:
            return jsonify({"success": False, "error": result})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route('/api/projects/<filename>', methods=['GET'])
def load_project(filename):
    try:
        project_data = config.load_project(filename)
        if project_data:
            return jsonify(project_data)
        else:
            return jsonify({"success": False, "error": "Project not found"})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route('/api/projects/<filename>', methods=['DELETE'])
def delete_project(filename):
    try:
        if config.delete_project(filename):
            return jsonify({"success": True})
        else:
            return jsonify({"success": False, "error": "Project not found or could not be deleted"})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route('/api/set_project', methods=['POST'])
def set_project():
    try:
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"})
        
        data = request.get_json()
        name = data.get('name', 'Untitled')
        # This is just a UI session state, maybe save to config later if needed
        # For now, we'll just acknowledge it
        return jsonify({"success": True, "name": name})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)})

@app.route('/api/upload_model', methods=['POST'])
def upload_model():
    try:
        if 'file' not in request.files:
            return jsonify({"success": False, "error": "No file part in request"})

        file = request.files['file']
        if not file or not file.filename:
            return jsonify({"success": False, "error": "No file selected"})

        filename = secure_filename(file.filename)
        lower_name = filename.lower()
        if not (lower_name.endswith('.stl') or lower_name.endswith('.3mf')):
            return jsonify({"success": False, "error": "Only .stl and .3mf files are allowed"})

        upload_dir = os.path.join(app.static_folder, "uploads")
        os.makedirs(upload_dir, exist_ok=True)

        if lower_name.endswith('.stl'):
            base_name, ext = os.path.splitext(filename)
            unique_name = f"{base_name}_{uuid.uuid4().hex[:8]}{ext.lower()}"
            abs_path = os.path.join(upload_dir, unique_name)
            file.save(abs_path)
            return jsonify({
                "success": True,
                "filename": unique_name,
                "url": f"/static/uploads/{unique_name}",
                "models": [{"filename": unique_name, "url": f"/static/uploads/{unique_name}"}]
            })

        base_name, _ = os.path.splitext(filename)
        models = _extract_3mf_models(file, upload_dir, secure_filename(base_name) or "model")
        if not models:
            return jsonify({"success": False, "error": "No mesh models found in 3MF file"})
        return jsonify({
            "success": True,
            "source": "3mf",
            "models": models
        })
    except Exception as e:
        return jsonify({"success": False, "error": "Upload failed"})

@app.route('/download_config', methods=['POST'])
def download_config():
    try:
        # Get endpoint URL from request
        if not request.is_json:
            return jsonify({"success": False, "error": "Content-Type must be application/json"})
        
        data = request.get_json()
        endpoint_url = data.get('endpoint_url', '').strip()
        
        if not endpoint_url:
            return jsonify({"success": False, "error": "No endpoint URL provided"})
        
        # Validate URL format
        if not endpoint_url.startswith(('http://', 'https://')):
            return jsonify({"success": False, "error": "Invalid URL format. Must start with http:// or https://"})
        
        # Try to download config
        try:
            download_url = endpoint_url
            if not download_url.endswith('/config.json'):
                if not download_url.endswith('/'):
                    download_url += '/'
                download_url += 'config.json'
                
            response = requests.get(download_url, timeout=10)
            response.raise_for_status()
            
            # Parse and validate the downloaded config
            downloaded_config = response.json()
            
            # Basic validation - check if it looks like a Katana config
            if not isinstance(downloaded_config, dict):
                return jsonify({"success": False, "error": "Invalid config format"})
            
            # Save the downloaded config
            config.config = downloaded_config
            config.save_config("config.json")
            
            return jsonify({
                "success": True, 
                "message": f"Config downloaded from {endpoint_url}",
                "config": downloaded_config
            })
            
        except requests.exceptions.RequestException as e:
            return jsonify({"success": False, "error": f"Failed to download: {str(e)}"})
        except json_module.JSONDecodeError:
            return jsonify({"success": False, "error": "Invalid JSON in downloaded config"})
            
    except Exception as e:
        return jsonify({"success": False, "error": "Internal server error"})


print("DO NOT RUN THIS SCRIPT DIRECTLY! USE main.py TO RUN KATANA!")
